# Generated by Django 5.1 on 2024-08-24 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_corpo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('corpo', models.TextField(max_length=1500)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
